apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: qbdcsci2t-python
  janus-idp.io/tekton: qbdcsci2t-python
  backstage.io/kubernetes-id: qbdcsci2t-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: qbdcsci2t-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
